module(
    name = "failsafe",
    version = "1.0.0",
    bazel_compatibility = [">=8.3.0"],
)

# Causes bazel-bin/external/rules_java+ to be created
# >=8.15.2 is required to have support for local JVMs ("java.local" below)
bazel_dep(name = "rules_java", version = "8.15.2")

java = use_extension("@rules_java//java:extensions.bzl", "java_repository")
# As documented in https://bazel.build/docs/bazel-and-java#config-java-toolchains
# Beware to use "Nightly" or > 8.3 in the doc's version dropdown at the top
java.local(
    name="zulu17",
    java_home = "/home/churlin/Downloads/zulu17.60.17-ca-jdk17.0.16-linux_x64/",
)
# Make the repo accessible from the current context
use_repo(java, "zulu17")
register_toolchains("@zulu17//:all")

bazel_dep(name = "rules_jvm_external", version = "6.8")
maven = use_extension("@rules_jvm_external//:extensions.bzl", "maven")
# Run `REPIN=1 bazel run @maven//:pin` to repin
maven.install(
    artifacts = [
      "com.squareup.okhttp3:okhttp:4.9.3",
      "com.squareup.retrofit2:retrofit:2.9.0",
      "io.reactivex:rxjava:1.0.12",
      "io.netty:netty-all:4.1.51.Final",
      "io.vertx:vertx-core:3.9.8",
      "org.testng:testng:6.9.10",
      "org.mockito:mockito-core:4.2.0",
    ],
    lock_file = "//:maven_install.json",
)
use_repo(maven, "maven")
