java_library(
    name = "okhttp",
    srcs = glob(["src/main/java/dev/failsafe/okhttp/*.java"]),
    deps = ["//core:failsafe",
            "@maven//:com_squareup_okhttp3_okhttp"
    ],
    visibility = ["//visibility:private"],
)
