java_library(
    name = "examples",
    srcs = glob(["src/main/java/dev/failsafe/examples/*.java"]),
    deps = [
        "//core:failsafe",
        "@maven//:io_reactivex_rxjava",
        "@maven//:io_netty_netty_all",
        "@maven//:io_vertx_vertx_core",
        "@maven//:org_testng_testng",
        "@maven//:org_mockito_mockito_core",
    ],
    visibility = ["//visibility:private"],
)
