java_library(
    name = "retrofit",
    srcs = glob(["src/main/java/dev/failsafe/retrofit/*.java"]),
    deps = ["//core:failsafe",
            "@maven//:com_squareup_retrofit2_retrofit"
    ],
    visibility = ["//visibility:private"],
)
